### ISSUE TITLE
Really need example | How to play mp3 file

### ISSUE THREAD

**Issue by Firues** [tcolgate/mp3#6]
Dear Tristan.
Can you give an example with comments? How to play mp3 file? (osx)
I know about the example( https://godoc.org/github.com/tcolgate/mp3#ex-Decoder-Decode), 
but it absolutely did not help me.
Please do not close the 	question, if you do not have time to give an example, maybe someone else will help.
Thank you very much!

**Comment by tcolgate** [comment]
The package only parses MP3 frame headers, it cannot be used for playback at this time

**Comment by Firues** [comment]
Oh, I'm stupid. Thank you.

But can you then tell me what I'd better use to solve my problem?
I just can not find it on the Internet.
(And after, of course, you(or me) can remove this issue.) Please?

**Comment by tcolgate** [comment]
I'm not aware of a pure Go mp3 decoder yet, (I may add it to this package one day, but not soon).
I've had some discussion about this with another user before, they ended up using libmpg123 and Cgo...
https://github.com/angadn/empeggo/blob/master/mpg123/mpg123.go
